default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:

development:
  <<: *default
  database: sim_near_blockchain_explorer_development

test:
  <<: *default
  database: sim_near_blockchain_explorer_test

production:
  <<: *default
  database: <%= ENV.fetch("PROD_DATABASE") { "sim_near_blockchain_explorer" } %>
  username: <%= ENV['PROD_DATABASE_USER'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %>
